### ISSUE TITLE
member cluster webhook setup

### ISSUE THREAD

**Issue by Wenfeng-GAO** [KusionStack/rollout#24]
## Feature Request

I'd like to propose the implementation of a member cluster webhook feature for the Rollout project. This webhook would introduce two key capabilities that can aid in platform presentation and observability, as well as grant more control to the rollout process during updates.

## Motivation

As the Rollout project aims to streamline and manage the deployment process in Kubernetes environments efficiently, having additional observability and control during the rollout process can significantly benefit users who wish to have more granular insights and management options. The proposed member cluster webhook would serve this purpose with the following functionalities:

1. **Batch Labeling for Updated Pods:** During the rolling update process, it would be beneficial to tag updated pods with labels indicating their batch group. This labeling can help in tracking which pods have been upgraded and to which batch they belong, effectively aiding platform display features and providing valuable information for observability purposes.

2. **Deployment Pause Before Upgrade:** To enable the Rollout controller to take over the upgrade process seamlessly, there should be a capability to pause the Deployment before it begins updating. This pause function would allow the Rollout controller to intercede and manage the deployment according to the defined strategy and parameters.

## Desired Capabilities

1. **Pod Labeling During Rolling Updates:**
   - The webhook should add a label to each pod during the rolling update process that identifies the specific batch group of the rollout.
   - This label can be used by monitoring tools and dashboards to display rollout progress and associated batch information.

2. **Control Over Deployment Updates:**
   - The webhook should be capable of pausing the Deployment before an update begins.
   - Once paused, the Rollout controller should detect this state and manage the rollout process according to its configuration.

**Comment by zoumo** [comment]
done
